#!/bin/bash

###############################################################################
#                               Bash Commands                                 #
###############################################################################

#
# extract - Archive extractor
# usage: extract <file>
#

extract ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


#
# distroArt - Distro specific screen art
# usage: distroArt
#

distroArt()
{

    if [ -x "$(command -v neofetch)" ]; then
        neofetch
    else
        echo "Download neofetch for distro ASCII art!"
    fi
}

###############################################################################
#                               Aliases and exports                           #
###############################################################################
alias v=/usr/local/bin/nvim
alias q=exit
alias cp="cp -i"               # confirm before overwriting something
alias df='df -h'               # human-readable sizes
alias free='free -m'           # show sizes in MB
alias grep='grep --colour=auto'
alias myde='source $envs/Setup_MyDE'
alias build='cd ~/Build'

# Git
alias git-log='git log --graph --decorate --all'

# PG settings
if [ -f ~/.pgrc ]; then
    source ~/.pgrc
fi

# User binaries
export PATH=~/.local/bin:$PATH

# My env variables
export envs=$HOME/Envs

###############################################################################
#                                   Main                                      #
###############################################################################
distroArt
