#!/bin/bash

source ~/.keyrc

alias killpg="lsof -i :3000 | grep ruby | awk '{print \$2}' | xargs kill -9"
alias grpc="cd ~/Dev/policygenius && bundle exec rails runner grpc_server.rb"
alias rubochopit="git diff --name-only origin/master | grep "\.rb$" | xargs -n 1 bin/bundle exec rubocop -a"
alias accordion='source $envs/Setup_Accordian'
alias accordion_admin='source $envs/Setup_Accordian-Admin'
alias policygenius='source $envs/Setup_PolicyGenius'
alias hotline='source $envs/Setup_HotLine'
alias umbrella='source $envs/Setup_Umbrella'
alias umbrella_automations='source $envs/Setup_UmbrellaAutomations'
