#!/bin/zsh

###############################################################################
#                               Bash Commands                                 #
###############################################################################

#
# extract - Archive extractor
# usage: extract <file>
#

extract ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


#
# distroArt - Distro specific screen art
# usage: distroArt
#

distroArt()
{

    if [ -x "$(command -v neofetch)" ]; then
        neofetch
    else
        echo "Download neofetch for distro ASCII art!"
    fi
}

###############################################################################
#                               Aliases and exports                           #
###############################################################################
alias v=/usr/bin/nvim
alias q=exit
alias cp="cp -i"               # confirm before overwriting something
alias df='df -h'               # human-readable sizes
alias free='free -m'           # show sizes in MB
alias grep='grep --colour=auto'
alias myde='cd $HOME/Dev/MyDE'
alias build='cd ~/Build'
alias dev='cd ~/Dev'
alias notes='cd ~/Documents/Notes'
alias pt=ptpython

# Git
alias gs='git log --graph --decorate --all'
alias gab="git ls-remote --heads origin | awk '{print \$2}' | cut -c 12-"
alias gdn='gd master --name-only | cat'
alias gdv='gd master --name-only | cat | xargs nvim -p'

# PG settings
if [ -f ~/.pgrc ]; then
    source ~/.pgrc
fi

# Exports
export envs=$HOME/Envs
export TERMINAL=konsole
export GOBIN=~/.local/share/go/bin
export GOPATH=~/.local/share/go/
export EDITOR=nvim
export VISUAL=nvim
export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab

# My PATH
export PATH=~/.local/bin:$PATH
export PATH=$GOBIN:$PATH
export PATH=/home/nate/Dev/staging/include/linux/:$PATH
export PATH=/home/nate/Dev/flutter/bin:$PATH
export PATH=/home/nate/Dev/flutter/bin/cache/dart-sdk/bin:$PATH
export PATH=/opt:$PATH
export PATH=/home/nate/.fonts:$PATH
export PATH=/home/nate/.asdf/installs/python/3.8.2/bin/:$PATH

# ZSH specifics
export ZSH="/home/nate/.oh-my-zsh"
export UPDATE_ZSH_DAYS=14
export LANG=en_US.UTF-8

# XDG config files
export XDG_CONFIG_DIRS=/etc/xdg/

ZSH_THEME="robbyrussell"

plugins=(
git
colored-man-pages
colorize
command-not-found
common-aliases
fzf
systemd
github
ruby
python
zsh-syntax-highlighting
docker
docker-compose
kubectl
zsh-autosuggestions
alias-tips
)

source $HOME/.bashrc
source $ZSH/oh-my-zsh.sh

###############################################################################
#                                   Main                                      #
###############################################################################
distroArt
