#!/bin/zsh

###############################################################################
#                               Bash Commands                                 #
###############################################################################

#
# extract - Archive extractor
# usage: extract <file>
#

extract ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


#
# distroArt - Distro specific screen art
# usage: distroArt
#

distroArt()
{

    if [ -x "$(command -v neofetch)" ]; then
        neofetch
    else
        echo "Download neofetch for distro ASCII art!"
    fi
}

###############################################################################
#                               Aliases and exports                           #
###############################################################################
alias v=/usr/bin/nvim
alias t='/usr/bin/tmux -f ~/.config/tmux/tmux.conf'
alias q=exit
alias cp="cp -i"               # confirm before overwriting something
alias df='df -h'               # human-readable sizes
alias free='free -m'           # show sizes in MB
alias grep='grep --colour=auto'
alias myde='cd $HOME/Development/MyDE'
alias build='cd ~/Build'
alias dev='cd ~/Development'
alias notes='cd ~/Documents/Notes'
alias docs='cd ~/Documents'

# Git
alias gs='git log --graph --decorate --all'
alias gdn='gd master --name-only | cat'
alias gdv='gd master --name-only | cat | xargs nvim -p'

# Exports
#export TERM=alacritty
export EDITOR=nvim
export VISUAL=nvim

# pyenv
#export PYENV_ROOT=$HOME/.pyenv
#export PATH=$PYENV_ROOT/bin:$PATH
#eval $(pyenv init --path)

# My PATH
export PATH=~/.local/bin:$PATH
export PATH=/opt:$PATH

# ZSH specifics
export ZSH="/home/nate/.oh-my-zsh"
export UPDATE_ZSH_DAYS=14
export LANG=en_US.UTF-8

ZSH_THEME="robbyrussell"

plugins=(
zsh-syntax-highlighting
zsh-autosuggestions
alias-tips
git
systemd
colored-man-pages
fzf
tmux
)

source $ZSH/oh-my-zsh.sh

###############################################################################
#                                   Main                                      #
###############################################################################
distroArt
