# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#!/bin/zsh

###############################################################################
#                               Bash Commands                                 #
###############################################################################

#
# extract - Archive extractor
# usage: extract <file>
#

extract ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


#
# distroArt - Distro specific screen art
# usage: distroArt
#

distroArt()
{

    if [ -x "$(command -v neofetch)" ]; then
        neofetch
    else
        echo "Download neofetch for distro ASCII art!"
    fi
}

###############################################################################
#                               Aliases and exports                           #
###############################################################################
alias v=lvim
alias t='/usr/bin/tmux -f ~/.config/tmux/tmux.conf'
alias q=exit
alias cp="cp -i"               # confirm before overwriting something
alias df='df -h'               # human-readable sizes
alias free='free -m'           # show sizes in MB
alias grep='grep --colour=auto'
alias myde='cd $HOME/Development/MyDE'
alias build='cd ~/Build'
alias dev='cd ~/Development'
alias notes='cd ~/Documents/Notes'
alias docs='cd ~/Documents'

# Git
alias gs='git log --graph --decorate --all'
alias gdn='gd master --name-only | cat'
alias gdv='gd master --name-only | cat | xargs nvim -p'

# Cmake
alias csb='cmake -S . -B ./build'
alias cb='cmake --build ./build'

# docker compose
alias dcb='docker-compose build'
alias dcup='docker-compose up'
alias dx='docker exec -it'
alias lzd='lazydocker'

# Exports
export EDITOR=lvim
export VISUAL=lvim

export PYTHONPATH=/home/gyory/Development/lava-dl/src/:$PYTHONPATH
export PYTHONPATH=/home/gyory/Development/lava/src/:$PYTHONPATH

# Java and Maven :(
export M2_HOME='/opt/apache-maven-3.9.4'
export PATH=$M2_HOME/bin:$PATH
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/

# GPT
export OPENAI_API_KEY=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

# pyenv
#export PYENV_ROOT=$HOME/.pyenv
#export PATH=$PYENV_ROOT/bin:$PATH
#eval $(pyenv init --path)
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# My PATH
export PATH=~/.local/bin:$PATH
export PATH=/opt:$PATH

# ZSH specifics
export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=14
export LANG=en_US.UTF-8

plugins=(
zsh-syntax-highlighting
zsh-autosuggestions
alias-tips
git
systemd
colored-man-pages
fzf
tmux
)

source $ZSH/oh-my-zsh.sh

# Source ROS environment
source /opt/ros/noetic/setup.zsh

###############################################################################
#                                   Main                                      #
###############################################################################
distroArt

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
